### ISSUE TITLE
Programování Micro Bitu v češtině

### ISSUE THREAD

**Issue by vsobotka** [xsuchy/programovani_pro_deti#4]
Dobrý den,
na workshopu PyConu jste měl prostředí pro programování Micro Bitu v češtině. Nedaří se mi toho docílit. Mohl byste mi, prosím, říct, jak na to?

**Comment by xsuchy** [comment]
Fungovalo a uz nefunguje. Zkusil jsem se zeptat zda bude nejaka nahrada.
http://translate.microbit.org/project/microbitorg/discussions/20
Samozrejme nejlepsi by bylo dotahnout preklad na 100 procent. Zkuste nam pomoct   http://translate.microbit.org/project/microbitorg/cs#

**Comment by xsuchy** [comment]
Resp. preklad editoru je zde https://crowdin.com/project/kindscript

**Comment by xsuchy** [comment]
Ha, už to mam.
https://makecode.microbit.org/beta?livelang=cs
A vidíte tam to co je ted preloženo. Hned v ramci nekolika sekund.
Akorat to dost prekopali tak se hodne veci musi prelozit znovu.

**Comment by vsobotka** [comment]
Super, díky. Budu se snažit pomoct s překladem.
